### ISSUE TITLE
PCI-E Gen. reported wrong

### ISSUE THREAD

**Issue by RhynarAI** [ProjectPhysX/OpenCL-Benchmark#11]
Thanx for your great work :)

Out of curiosity, I just ran the benchmark on an older GCN2 headless Server Card (S9150). The card itself has a GEN 3 PCIE 16x Connector - but is sitting in a GEN 4 Motherboard. The Benchmark reports this:

.-----------------------------------------------------------------------------.
|----------------.------------------------------------------------------------|
| Device ID    0 | Intel(R) UHD Graphics                                      |
| Device ID    1 | Hawaii                                                     |
| Device ID    2 | Genuine Intel(R) CPU 0000 @ 2.20GHz                        |
|----------------'------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID      | 1                                                          |
| Device Name    | Hawaii                                                     |
| Device Vendor  | Advanced Micro Devices, Inc.                               |
| Device Driver  | 3240.7 (Windows)                                           |
| OpenCL Version | OpenCL C 2.0                                               |
| Compute Units  | 44 at 1250 MHz (2816 cores, 7.040 TFLOPs/s)                |
| Memory, Cache  | 16384 MB, 16 KB global / 32 KB local                       |
| Buffer Limits  | 13708 MB global, 14037811 KB constant                      |
|----------------'------------------------------------------------------------|
| Info: OpenCL C code successfully compiled.                                  |
| FP64  compute                                         2.302 TFLOPs/s (1/3 ) |
| FP32  compute                                         4.674 TFLOPs/s (2/3 ) |
| FP16  compute                                          not supported        |
| INT64 compute                                         0.423  TIOPs/s (1/16) |
| INT32 compute                                         1.643  TIOPs/s (1/4 ) |
| INT16 compute                                         3.185  TIOPs/s (1/2 ) |
| INT8  compute                                         3.155  TIOPs/s (1/2 ) |
| Memory Bandwidth ( coalesced read      )                        317.92 GB/s |
| Memory Bandwidth ( coalesced      write)                        207.06 GB/s |
| Memory Bandwidth (misaligned read      )                        302.12 GB/s |
| Memory Bandwidth (misaligned      write)                        102.00 GB/s |
| PCIe   Bandwidth (send                 )                          9.99 GB/s |
| PCIe   Bandwidth (   receive           )                         10.62 GB/s |
| PCIe   Bandwidth (        bidirectional)            **(Gen4 x16)**   10.27 GB/s |
|-----------------------------------------------------------------------------|
|-----------------------------------------------------------------------------|
| Done. Press Enter to exit.                                                  |
'-----------------------------------------------------------------------------'

**Comment by ProjectPhysX** [comment]
Hi @RhynarAI,

the PCIe generation is just an estimate based on measured bandwidth. The benchmark sends a 1GB buffer back and forth many times and measures fastest copy time. Gen3 x16 is peak 16GB/s bidirectional, and peak 8GB/s single-directional. If any of the two is measured significantly higher, the estimate reports Gen4 x16. Not sure how 10.62 GB/s is possible on your system :)

Kind regards,
Moritz

**Comment by RhynarAI** [comment]
Thanx for getting back.

Ah ok, the PCI-e specs are derived from the measurement... This could be misleading - GEN 4 4x can be similar to GEN 3 8x or GEN 2 16x... 
PCI-E specs could be drawn from the driver (like GPU-Z) - but that may be difficult or not necessary. Maybe just get rid of the "PCIE Assumption" to avoid confusion ?

Kind regards
