### ISSUE TITLE
FP16 support is determined incorrectly.

### ISSUE THREAD

**Issue by stolk** [ProjectPhysX/OpenCL-Benchmark#2]
Running this on nvidia RTX3070 or amd RX580, the benchmark claims that FP16 is not supported.

I doubt that is correct, though.

If I hard-code the value of `is_fp16_capable = 1` then the FP16 benchmark works just fine.

This may have to do that some extensions get promoted to the standard, and could no longer show up?

**Comment by ProjectPhysX** [comment]
Hi @stolk,

Nvidia indeed recently added support for FP16/half arithmetic support in OpenCL (see 2.8.1.1 in the [driver release notes](https://us.download.nvidia.com/Windows/531.68/531.68-win11-win10-release-notes.pdf)). However, the `cl_khr_fp16` flag is stll not reported, and `CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF` / `CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF` both show up as `0`, so to the outside it looks as if FP16/half arithmetic was not supported. For AMD's Mesa drivers it's the same, but in AMD's ROCm / HSA1.1,LC drivers the flags are set correct.

There is unfortunately no way to detect FP16/half support of the driver flags are wrongly reported. I will contact Nvidia/AMD and see if they fix this.

Regards,
Moritz

**Comment by stolk** [comment]
Ok, thanks. I am on linux, by the way.

Also I should mention: forcefully setting fp16 support to 1 only worked on AMD. When I tried that on nvidia, the benchmark run was compromised. So on OpenCL 3.0 CUDA 12.1.68 the report of no-support is actually correct. I naively thought that all modern GPUs would do fp16 on OpenCL, but no.

**Comment by sumseq** [comment]
Just FYI, on my RADEON VII, the FP16 is auto-detected correctly:
"| FP16  compute                                        25.512 TFLOPs/s ( 2x ) |"

This was with:
```
| Device Driver  | 3513.0 (HSA1.1,LC)                                         |
| OpenCL Version | OpenCL C 2.0   
```
