### ISSUE TITLE
CUDA_VISIBLE_DEVICES disables CPU and other GPU benchmarks

### ISSUE THREAD

**Issue by sumseq** [ProjectPhysX/OpenCL-Benchmark#3]
Whenever I have CUDA_VISIBLE_DEVICES set, the benchmark will only run thsoe NVIDIA devices and will ignore the CPU and any other GPUs (e.g. AMD).

I understand using CUDA_VISIBLE_DEVICES to limit the NVIDIA devices the benchmark sees, but I do not think it shoudl disable other devices.

**Comment by ProjectPhysX** [comment]
This is expected: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

In short: don't use `CUDA_VISIBLE_DEVICES`.
