### ISSUE TITLE
Type support needs to check the extensions only.

### ISSUE THREAD

**Issue by jungpark-mlir** [ProjectPhysX/OpenCL-Benchmark#4]
https://github.com/ProjectPhysX/OpenCL-Benchmark/blob/a03622915fa7ac4839d7a8591f0e018f30a78638/src/opencl.hpp#L46

Hello,

I've been learning how it works and have some questions about it.
Firstly, I'm not sure about the logic it determines the support for the data types.
I believe CL_DEVICE_NATIVE_VECTOR_WIDTH_* doesn't necessarily reflect the presence of a given type support.

The specification only says,
```
If double precision is not supported, CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE must return 0.
If the cl_khr_fp16 extension is not supported,CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF must return 0.
```
Not the other way around.
Checking support for the double/half types only need to query cl_khr_fp64, cl_khr_fp16 extensions respectively.
Also I wonder if the other types need to be checked because they're supposed to be supported as builtin scalar type.

I might be missing something but please have a look and let me know what you think about it.

**Comment by ProjectPhysX** [comment]
Hi @jungpark-mlir,

the `CL_DEVICE_NATIVE_` provide the size of the vector units which can sometimes be useful information. For Intel Arc GPUs I had to add an additional failsafe: They would happily report `CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE = 1`, indicating FP64 support, but the `cl_khr_fp64` flag is missing and they don't support FP64 in hardware. Same for FP16.

The other data types are always present.

Regards,
Moritz

**Comment by lorn10** [comment]
@jungpark-mlir Just FYI, maybe you will look at some point into the new Mesa OpenCL implementation called "**rusticl**", - if you are on Linux. :wink: The initial support looks to be [really promising](https://www.phoronix.com/review/intel-arc-march23).

I think Mesa's open-source "rusticl" doesn't have those restrictions which some vendor specific OpenCL implementations have. And yes also Intel seems to limit the compute capability of their hardware for whatever reason. I don't understand why those newest Intel GPU are lacking hardware FP64 support, - any software FP64 emulation would be much slower. But in the end this should have not a big relevance for gaming, - it might have one for mining. :smile:
