### ISSUE TITLE
Question: Anyway to force cpu on Arm?

### ISSUE THREAD

**Issue by StuartIanNaylor** [ProjectPhysX/OpenCL-Benchmark#8]
In the heading really, but anyway to bench the cpu so you can make comparisons?

**Comment by ProjectPhysX** [comment]
Most ARM CPUs don't have an OpenCL Runtime from the vendor, so they don't show up as OpenCL devices. But you can try if the [PoCL](https://github.com/pocl/pocl) Runtime works with your particular ARM CPU model.

**Comment by StuartIanNaylor** [comment]
Its ok but I did look at Pocl but had a gut feeling even if it runs it might not be well optimised for Arm achitecture and compares would be more about code optimisation than hardware...
I don't think I will bother but good to know as will stop me searching.
It was just a reddit discussion where another is stating a Mali G610 mc4 is 19x faster for ML than the 4 core cortex A76.
If I use ArmNN and swap the delegate from CPU to GPU then the GPU still manages 75% that the CPU can with wav2letter.
The argument turned to that Arms Mali code was just not optimised, but think probably the oppisite the CPU code from Arm is likely heavily optimised and on the RK3588 SoC probably what I was sort of expecting as Nvidia it aint.

I guess its sort of an impossible compare as which are you comparing CPU or GPU or the code optimisation behind each but a bench for TFLOPs/s on CPU would be interesting at least for a reddit argument :)

Thanks 

_Building on ARM platforms is possible but lacks a maintainer and there are [some gotchas](https://github.com/pocl/pocl/blob/main/README.ARM)._
